---
language: python
services: docker

install:
  - pip install molecule docker

before_script:
  - cd ansible/roles/install-jenkins

script:
  - molecule test

after_script:
  - sudo netstat -plnt
  - molecule destroy
