---
galaxy_info:
  author: shazChaudhry
  description: Jenkins CI
  company: https://www.linkedin.com/in/shahzad-chaudhry/

  issue_tracker_url: https://github.com/shazChaudhry/Equal_Experts_tech_test

  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 2.7

  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - jenkins
    - ci

dependencies:
  - role: geerlingguy.java
    when: "ansible_os_family == 'RedHat'"
    vars:
      java_packages: java-1.8.0-openjdk
