---
- name: Prepare
  hosts: all
  gather_facts: false
  become: true
  vars:
    yum_packages:
      - python-pip
      - jq
      - git
      - gcc
      - python-devel
      - openssl-devel
      - libselinux-python
      - net-tools
      # - java-1.8.0-openjdk-devel

  tasks:
    - name: Enable EPEL repository
      yum:
        name: epel-release
        state: latest
    - name: install required yum packages
      yum:
        name: "{{ yum_packages }}"
        state: latest
    - name: Install python docker module
      pip:
        name: docker
